"""create_booking_engine_configs_table

Revision ID: 4ac0574b7fd3
Revises: 3a47fcd4f8b0
Create Date: 2025-10-19 08:02:12.388101-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac0574b7fd3'
down_revision = '3a47fcd4f8b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_engine_configs',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('custom_slug', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('welcome_text', sa.Text(), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('gallery_photos', sa.JSON(), nullable=True),
    sa.Column('hero_photos', sa.JSON(), nullable=True),
    sa.Column('testimonials', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('privacy_policy', sa.Text(), nullable=True),
    sa.Column('check_in_time', sa.String(length=5), nullable=False),
    sa.Column('check_out_time', sa.String(length=5), nullable=False),
    sa.Column('require_prepayment', sa.Boolean(), nullable=False),
    sa.Column('prepayment_percentage', sa.Integer(), nullable=True),
    sa.Column('instant_booking', sa.Boolean(), nullable=False),
    sa.Column('default_min_stay', sa.Integer(), nullable=False),
    sa.Column('default_max_stay', sa.Integer(), nullable=True),
    sa.Column('min_advance_booking_hours', sa.Integer(), nullable=False),
    sa.Column('max_advance_booking_days', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('notification_emails', sa.String(length=500), nullable=True),
    sa.Column('send_sms_confirmation', sa.Boolean(), nullable=False),
    sa.Column('send_whatsapp_confirmation', sa.Boolean(), nullable=False),
    sa.Column('available_extras', sa.JSON(), nullable=True),
    sa.Column('available_languages', sa.JSON(), nullable=True),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('google_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('facebook_pixel_id', sa.String(length=50), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('custom_js', sa.Text(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_booking_engine_configs_property_id_properties')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_booking_engine_configs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_engine_configs')),
    sa.UniqueConstraint('property_id', 'tenant_id', name='unique_booking_config_per_property')
    )
    op.create_index(op.f('ix_booking_engine_configs_custom_slug'), 'booking_engine_configs', ['custom_slug'], unique=True)
    op.create_index(op.f('ix_booking_engine_configs_id'), 'booking_engine_configs', ['id'], unique=False)
    op.create_index(op.f('ix_booking_engine_configs_is_active'), 'booking_engine_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_booking_engine_configs_property_id'), 'booking_engine_configs', ['property_id'], unique=False)
    op.create_index(op.f('ix_booking_engine_configs_tenant_id'), 'booking_engine_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_engine_configs_tenant_id'), table_name='booking_engine_configs')
    op.drop_index(op.f('ix_booking_engine_configs_property_id'), table_name='booking_engine_configs')
    op.drop_index(op.f('ix_booking_engine_configs_is_active'), table_name='booking_engine_configs')
    op.drop_index(op.f('ix_booking_engine_configs_id'), table_name='booking_engine_configs')
    op.drop_index(op.f('ix_booking_engine_configs_custom_slug'), table_name='booking_engine_configs')
    op.drop_table('booking_engine_configs')
    # ### end Alembic commands ###