"""add_reservation_restrictions_table_fixed

Revision ID: 695c4db255b5
Revises: 4ac0bb90abcb
Create Date: 2025-10-02 22:42:37.230601-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695c4db255b5'
down_revision = '4ac0bb90abcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_restrictions',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('restriction_type', sa.String(length=30), nullable=False),
    sa.Column('restriction_value', sa.Integer(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('channel_manager_id', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('sync_pending', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.String(length=30), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('channel_settings', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_reservation_restrictions_property_id_properties')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reservation_restrictions_room_id_rooms')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], name=op.f('fk_reservation_restrictions_room_type_id_room_types')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reservation_restrictions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_restrictions')),
    sa.UniqueConstraint('tenant_id', 'property_id', 'room_type_id', 'room_id', 'date_from', 'date_to', 'restriction_type', name='uq_restriction_scope_period_type')
    )
    op.create_index('idx_restrictions_date_range', 'reservation_restrictions', ['date_from', 'date_to', 'is_active'], unique=False)
    op.create_index('idx_restrictions_property_dates', 'reservation_restrictions', ['property_id', 'date_from', 'date_to'], unique=False)
    op.create_index('idx_restrictions_room_dates', 'reservation_restrictions', ['room_id', 'date_from', 'date_to'], unique=False)
    op.create_index('idx_restrictions_room_type_dates', 'reservation_restrictions', ['room_type_id', 'date_from', 'date_to'], unique=False)
    op.create_index('idx_restrictions_sync_pending', 'reservation_restrictions', ['sync_pending', 'last_sync_at'], unique=False)
    op.create_index('idx_restrictions_type_active', 'reservation_restrictions', ['restriction_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_channel_manager_id'), 'reservation_restrictions', ['channel_manager_id'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_date_from'), 'reservation_restrictions', ['date_from'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_date_to'), 'reservation_restrictions', ['date_to'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_id'), 'reservation_restrictions', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_is_active'), 'reservation_restrictions', ['is_active'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_priority'), 'reservation_restrictions', ['priority'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_property_id'), 'reservation_restrictions', ['property_id'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_restriction_type'), 'reservation_restrictions', ['restriction_type'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_room_id'), 'reservation_restrictions', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_room_type_id'), 'reservation_restrictions', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_source'), 'reservation_restrictions', ['source'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_sync_pending'), 'reservation_restrictions', ['sync_pending'], unique=False)
    op.create_index(op.f('ix_reservation_restrictions_tenant_id'), 'reservation_restrictions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_restrictions_tenant_id'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_sync_pending'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_source'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_room_type_id'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_room_id'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_restriction_type'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_property_id'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_priority'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_is_active'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_id'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_date_to'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_date_from'), table_name='reservation_restrictions')
    op.drop_index(op.f('ix_reservation_restrictions_channel_manager_id'), table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_type_active', table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_sync_pending', table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_room_type_dates', table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_room_dates', table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_property_dates', table_name='reservation_restrictions')
    op.drop_index('idx_restrictions_date_range', table_name='reservation_restrictions')
    op.drop_table('reservation_restrictions')
    # ### end Alembic commands ###