"""Add gender, address_number, neighborhood to guests

Revision ID: 34b27689c905
Revises: d85232471f05
Create Date: 2025-09-05 00:12:50.633533+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b27689c905'
down_revision = 'd85232471f05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('guests', sa.Column('address_number', sa.String(length=20), nullable=True))
    op.add_column('guests', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'neighborhood')
    op.drop_column('guests', 'address_number')
    op.drop_column('guests', 'gender')
    # ### end Alembic commands ###