"""Update rate plans model

Revision ID: e8d02b52de46
Revises: 79e02fa9710a
Create Date: 2025-10-02 20:35:21.406017-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d02b52de46'
down_revision = '79e02fa9710a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wubook_rate_plans', sa.Column('room_type_id', sa.Integer(), nullable=True))
    op.add_column('wubook_rate_plans', sa.Column('property_id', sa.Integer(), nullable=True))
    op.add_column('wubook_rate_plans', sa.Column('rate_plan_code', sa.String(length=50), nullable=False))
    op.add_column('wubook_rate_plans', sa.Column('rate_plan_type', sa.String(length=30), nullable=False))
    op.add_column('wubook_rate_plans', sa.Column('pricing_mode', sa.String(length=20), nullable=False))
    op.add_column('wubook_rate_plans', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.alter_column('wubook_rate_plans', 'configuration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('wubook_rate_plans', 'wubook_rate_plan_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wubook_rate_plans', 'valid_from',
               existing_type=sa.DATE(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('wubook_rate_plans', 'valid_to',
               existing_type=sa.DATE(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_constraint('uq_wubook_rate_plan_code', 'wubook_rate_plans', type_='unique')
    op.create_index(op.f('ix_wubook_rate_plans_is_default'), 'wubook_rate_plans', ['is_default'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_property_id'), 'wubook_rate_plans', ['property_id'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_rate_plan_code'), 'wubook_rate_plans', ['rate_plan_code'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_room_type_id'), 'wubook_rate_plans', ['room_type_id'], unique=False)
    op.create_unique_constraint('uq_rate_plan_code', 'wubook_rate_plans', ['tenant_id', 'rate_plan_code'])
    op.create_unique_constraint('uq_rate_plan_code_alias', 'wubook_rate_plans', ['tenant_id', 'code'])
    op.create_foreign_key(op.f('fk_wubook_rate_plans_property_id_properties'), 'wubook_rate_plans', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(op.f('fk_wubook_rate_plans_room_type_id_room_types'), 'wubook_rate_plans', 'room_types', ['room_type_id'], ['id'])
    op.drop_column('wubook_rate_plans', 'plan_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wubook_rate_plans', sa.Column('plan_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_wubook_rate_plans_room_type_id_room_types'), 'wubook_rate_plans', type_='foreignkey')
    op.drop_constraint(op.f('fk_wubook_rate_plans_property_id_properties'), 'wubook_rate_plans', type_='foreignkey')
    op.drop_constraint('uq_rate_plan_code_alias', 'wubook_rate_plans', type_='unique')
    op.drop_constraint('uq_rate_plan_code', 'wubook_rate_plans', type_='unique')
    op.drop_index(op.f('ix_wubook_rate_plans_room_type_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_rate_plan_code'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_property_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_is_default'), table_name='wubook_rate_plans')
    op.create_unique_constraint('uq_wubook_rate_plan_code', 'wubook_rate_plans', ['tenant_id', 'configuration_id', 'code'])
    op.alter_column('wubook_rate_plans', 'valid_to',
               existing_type=sa.String(length=30),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('wubook_rate_plans', 'valid_from',
               existing_type=sa.String(length=30),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('wubook_rate_plans', 'wubook_rate_plan_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wubook_rate_plans', 'configuration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('wubook_rate_plans', 'is_default')
    op.drop_column('wubook_rate_plans', 'pricing_mode')
    op.drop_column('wubook_rate_plans', 'rate_plan_type')
    op.drop_column('wubook_rate_plans', 'rate_plan_code')
    op.drop_column('wubook_rate_plans', 'property_id')
    op.drop_column('wubook_rate_plans', 'room_type_id')
    # ### end Alembic commands ###