"""create_reservation_restrictions_table

Revision ID: 4ac0bb90abcb
Revises: e8d02b52de46
Create Date: 2025-10-02 22:16:07.508576-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac0bb90abcb'
down_revision = 'e8d02b52de46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###