"""create payment_methods and sales_channels tables

Revision ID: 9d17558ad3df
Revises: 34b27689c905
Create Date: 2025-09-12 07:48:16.896088-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d17558ad3df'
down_revision = '34b27689c905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_reference', sa.Boolean(), nullable=True),
    sa.Column('has_fees', sa.Boolean(), nullable=True),
    sa.Column('default_fee_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payment_methods_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_payment_method_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_payment_method_tenant_name')
    )
    op.create_index(op.f('ix_payment_methods_code'), 'payment_methods', ['code'], unique=False)
    op.create_index(op.f('ix_payment_methods_display_order'), 'payment_methods', ['display_order'], unique=False)
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_is_active'), 'payment_methods', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_methods_name'), 'payment_methods', ['name'], unique=False)
    op.create_index(op.f('ix_payment_methods_tenant_id'), 'payment_methods', ['tenant_id'], unique=False)
    op.create_table('sales_channels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=True),
    sa.Column('base_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_api_integration', sa.Boolean(), nullable=True),
    sa.Column('api_config', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('business_rules', sa.JSON(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_channels_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_channels')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_sales_channel_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_sales_channel_tenant_name')
    )
    op.create_index(op.f('ix_sales_channels_channel_type'), 'sales_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_sales_channels_code'), 'sales_channels', ['code'], unique=False)
    op.create_index(op.f('ix_sales_channels_display_order'), 'sales_channels', ['display_order'], unique=False)
    op.create_index(op.f('ix_sales_channels_id'), 'sales_channels', ['id'], unique=False)
    op.create_index(op.f('ix_sales_channels_is_active'), 'sales_channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_sales_channels_name'), 'sales_channels', ['name'], unique=False)
    op.create_index(op.f('ix_sales_channels_tenant_id'), 'sales_channels', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_channels_tenant_id'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_name'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_is_active'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_id'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_display_order'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_code'), table_name='sales_channels')
    op.drop_index(op.f('ix_sales_channels_channel_type'), table_name='sales_channels')
    op.drop_table('sales_channels')
    op.drop_index(op.f('ix_payment_methods_tenant_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_name'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_is_active'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_display_order'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_code'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###