"""add_address_field_to_properties

Revision ID: f56b43264e8a
Revises: 4ac0574b7fd3
Create Date: 2025-10-19 08:58:09.641523-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56b43264e8a'
down_revision = '4ac0574b7fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.String(length=200), nullable=True))
    op.alter_column('properties', 'address_line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('reservations', sa.Column('public_token', sa.String(length=100), nullable=True))
    op.add_column('reservations', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('reservations', sa.Column('guest_name', sa.String(length=200), nullable=True))
    op.add_column('reservations', sa.Column('guest_email', sa.String(length=255), nullable=True))
    op.add_column('reservations', sa.Column('guest_phone', sa.String(length=20), nullable=True))
    op.add_column('reservations', sa.Column('guest_document', sa.String(length=20), nullable=True))
    op.add_column('reservations', sa.Column('booking_source', sa.String(length=50), nullable=True))
    op.add_column('reservations', sa.Column('sales_channel_name', sa.String(length=100), nullable=True))
    op.add_column('reservations', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('reservations', sa.Column('special_requests', sa.Text(), nullable=True))
    op.add_column('reservations', sa.Column('booking_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_reservations_public_token'), 'reservations', ['public_token'], unique=True)
    op.create_index(op.f('ix_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_foreign_key(op.f('fk_reservations_room_id_rooms'), 'reservations', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reservations_room_id_rooms'), 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_room_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_public_token'), table_name='reservations')
    op.drop_column('reservations', 'booking_metadata')
    op.drop_column('reservations', 'special_requests')
    op.drop_column('reservations', 'payment_method')
    op.drop_column('reservations', 'sales_channel_name')
    op.drop_column('reservations', 'booking_source')
    op.drop_column('reservations', 'guest_document')
    op.drop_column('reservations', 'guest_phone')
    op.drop_column('reservations', 'guest_email')
    op.drop_column('reservations', 'guest_name')
    op.drop_column('reservations', 'room_id')
    op.drop_column('reservations', 'public_token')
    op.alter_column('properties', 'address_line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###