"""create wubook tables

Revision ID: 43d4819887f0
Revises: ef329ce616a4
Create Date: 2025-09-14 11:04:42.817432-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d4819887f0'
down_revision = 'ef329ce616a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wubook_configurations',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('wubook_token', sa.String(length=255), nullable=False),
    sa.Column('wubook_lcode', sa.String(length=20), nullable=False),
    sa.Column('wubook_property_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.String(length=30), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.String(length=30), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('sync_availability', sa.Boolean(), nullable=False),
    sa.Column('sync_rates', sa.Boolean(), nullable=False),
    sa.Column('sync_restrictions', sa.Boolean(), nullable=False),
    sa.Column('sync_bookings', sa.Boolean(), nullable=False),
    sa.Column('auto_confirm_bookings', sa.Boolean(), nullable=False),
    sa.Column('channel_mappings', sa.JSON(), nullable=True),
    sa.Column('rate_multiplier', sa.JSON(), nullable=True),
    sa.Column('default_restrictions', sa.JSON(), nullable=True),
    sa.Column('api_settings', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_wubook_configurations_property_id_properties')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wubook_configurations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wubook_configurations')),
    sa.UniqueConstraint('tenant_id', 'property_id', name='uq_wubook_config_property'),
    sa.UniqueConstraint('tenant_id', 'wubook_lcode', name='uq_wubook_config_lcode')
    )
    op.create_index(op.f('ix_wubook_configurations_id'), 'wubook_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_wubook_configurations_is_active'), 'wubook_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_wubook_configurations_property_id'), 'wubook_configurations', ['property_id'], unique=False)
    op.create_index(op.f('ix_wubook_configurations_tenant_id'), 'wubook_configurations', ['tenant_id'], unique=False)
    op.create_table('wubook_rate_plans',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('wubook_rate_plan_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('parent_rate_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('derivation_type', sa.String(length=20), nullable=True),
    sa.Column('derivation_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('applicable_days', sa.JSON(), nullable=True),
    sa.Column('available_channels', sa.JSON(), nullable=True),
    sa.Column('min_stay', sa.Integer(), nullable=False),
    sa.Column('max_stay', sa.Integer(), nullable=True),
    sa.Column('min_advance_days', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=True),
    sa.Column('base_rate_single', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_rate_double', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_rate_triple', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_rate_quad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_adult_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_child_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cancellation_policy', sa.JSON(), nullable=True),
    sa.Column('payment_policy', sa.JSON(), nullable=True),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('yield_enabled', sa.Boolean(), nullable=False),
    sa.Column('yield_rules', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.String(length=30), nullable=True),
    sa.Column('last_rate_update', sa.String(length=30), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('wubook_data', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['wubook_configurations.id'], name=op.f('fk_wubook_rate_plans_configuration_id_wubook_configurations')),
    sa.ForeignKeyConstraint(['parent_rate_plan_id'], ['wubook_rate_plans.id'], name=op.f('fk_wubook_rate_plans_parent_rate_plan_id_wubook_rate_plans')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wubook_rate_plans_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wubook_rate_plans')),
    sa.UniqueConstraint('tenant_id', 'configuration_id', 'code', name='uq_wubook_rate_plan_code'),
    sa.UniqueConstraint('tenant_id', 'configuration_id', 'wubook_rate_plan_id', name='uq_wubook_rate_plan')
    )
    op.create_index(op.f('ix_wubook_rate_plans_code'), 'wubook_rate_plans', ['code'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_configuration_id'), 'wubook_rate_plans', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_id'), 'wubook_rate_plans', ['id'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_is_active'), 'wubook_rate_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_parent_rate_plan_id'), 'wubook_rate_plans', ['parent_rate_plan_id'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_tenant_id'), 'wubook_rate_plans', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wubook_rate_plans_wubook_rate_plan_id'), 'wubook_rate_plans', ['wubook_rate_plan_id'], unique=False)
    op.create_table('wubook_room_mappings',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('wubook_room_id', sa.String(length=50), nullable=False),
    sa.Column('wubook_room_name', sa.String(length=200), nullable=True),
    sa.Column('wubook_room_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_syncing', sa.Boolean(), nullable=False),
    sa.Column('sync_availability', sa.Boolean(), nullable=False),
    sa.Column('sync_rates', sa.Boolean(), nullable=False),
    sa.Column('sync_restrictions', sa.Boolean(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('standard_occupancy', sa.Integer(), nullable=True),
    sa.Column('min_occupancy', sa.Integer(), nullable=False),
    sa.Column('base_rate_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_multiplier', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('last_availability_sync', sa.String(length=30), nullable=True),
    sa.Column('last_rate_sync', sa.String(length=30), nullable=True),
    sa.Column('last_restriction_sync', sa.String(length=30), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_error_count', sa.Integer(), nullable=False),
    sa.Column('wubook_data', sa.JSON(), nullable=True),
    sa.Column('rate_plan_ids', sa.JSON(), nullable=True),
    sa.Column('room_settings', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['wubook_configurations.id'], name=op.f('fk_wubook_room_mappings_configuration_id_wubook_configurations')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_wubook_room_mappings_room_id_rooms')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wubook_room_mappings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wubook_room_mappings')),
    sa.UniqueConstraint('tenant_id', 'configuration_id', 'room_id', name='uq_wubook_mapping_room'),
    sa.UniqueConstraint('tenant_id', 'configuration_id', 'wubook_room_id', name='uq_wubook_mapping_wubook_room')
    )
    op.create_index(op.f('ix_wubook_room_mappings_configuration_id'), 'wubook_room_mappings', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_wubook_room_mappings_id'), 'wubook_room_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_wubook_room_mappings_is_active'), 'wubook_room_mappings', ['is_active'], unique=False)
    op.create_index(op.f('ix_wubook_room_mappings_room_id'), 'wubook_room_mappings', ['room_id'], unique=False)
    op.create_index(op.f('ix_wubook_room_mappings_tenant_id'), 'wubook_room_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wubook_room_mappings_wubook_room_id'), 'wubook_room_mappings', ['wubook_room_id'], unique=False)
    op.create_table('wubook_sync_logs',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('date_from', sa.String(length=10), nullable=True),
    sa.Column('date_to', sa.String(length=10), nullable=True),
    sa.Column('room_ids', sa.JSON(), nullable=True),
    sa.Column('rate_plan_ids', sa.JSON(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('success_items', sa.Integer(), nullable=False),
    sa.Column('error_items', sa.Integer(), nullable=False),
    sa.Column('skipped_items', sa.Integer(), nullable=False),
    sa.Column('changes_made', sa.JSON(), nullable=True),
    sa.Column('conflicts_found', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=False),
    sa.Column('data_transferred_kb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['wubook_configurations.id'], name=op.f('fk_wubook_sync_logs_configuration_id_wubook_configurations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_wubook_sync_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wubook_sync_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wubook_sync_logs'))
    )
    op.create_index('ix_wubook_sync_log_date', 'wubook_sync_logs', ['configuration_id', 'sync_type', 'started_at'], unique=False)
    op.create_index('ix_wubook_sync_log_status', 'wubook_sync_logs', ['configuration_id', 'status', 'started_at'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_configuration_id'), 'wubook_sync_logs', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_id'), 'wubook_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_status'), 'wubook_sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_sync_direction'), 'wubook_sync_logs', ['sync_direction'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_sync_type'), 'wubook_sync_logs', ['sync_type'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_tenant_id'), 'wubook_sync_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wubook_sync_logs_user_id'), 'wubook_sync_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wubook_sync_logs_user_id'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_tenant_id'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_sync_type'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_sync_direction'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_status'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_id'), table_name='wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_sync_logs_configuration_id'), table_name='wubook_sync_logs')
    op.drop_index('ix_wubook_sync_log_status', table_name='wubook_sync_logs')
    op.drop_index('ix_wubook_sync_log_date', table_name='wubook_sync_logs')
    op.drop_table('wubook_sync_logs')
    op.drop_index(op.f('ix_wubook_room_mappings_wubook_room_id'), table_name='wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_room_mappings_tenant_id'), table_name='wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_room_mappings_room_id'), table_name='wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_room_mappings_is_active'), table_name='wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_room_mappings_id'), table_name='wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_room_mappings_configuration_id'), table_name='wubook_room_mappings')
    op.drop_table('wubook_room_mappings')
    op.drop_index(op.f('ix_wubook_rate_plans_wubook_rate_plan_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_tenant_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_parent_rate_plan_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_is_active'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_configuration_id'), table_name='wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_rate_plans_code'), table_name='wubook_rate_plans')
    op.drop_table('wubook_rate_plans')
    op.drop_index(op.f('ix_wubook_configurations_tenant_id'), table_name='wubook_configurations')
    op.drop_index(op.f('ix_wubook_configurations_property_id'), table_name='wubook_configurations')
    op.drop_index(op.f('ix_wubook_configurations_is_active'), table_name='wubook_configurations')
    op.drop_index(op.f('ix_wubook_configurations_id'), table_name='wubook_configurations')
    op.drop_table('wubook_configurations')
    # ### end Alembic commands ###