"""add wubook sync fields to room_availability

Revision ID: 79e02fa9710a
Revises: 43d4819887f0
Create Date: 2025-09-14 15:42:13.522447-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e02fa9710a'
down_revision = '43d4819887f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_availability', sa.Column('sync_pending', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('room_availability', sa.Column('wubook_synced', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('room_availability', sa.Column('wubook_sync_error', sa.Text(), nullable=True))
    op.add_column('room_availability', sa.Column('last_wubook_sync', sa.DateTime(), nullable=True))
    op.add_column('room_availability', sa.Column('is_bookable', sa.Boolean(), nullable=False, server_default='true'))
    
    # Atualizar registros existentes com valores calculados
    op.execute("""
        UPDATE room_availability 
        SET 
            is_bookable = (
                is_available = true 
                AND is_blocked = false 
                AND is_out_of_order = false 
                AND is_maintenance = false 
                AND is_reserved = false
            ),
            sync_pending = true
        WHERE is_active = true
    """)
    
    op.create_index(op.f('ix_room_availability_is_bookable'), 'room_availability', ['is_bookable'], unique=False)
    op.create_index(op.f('ix_room_availability_last_wubook_sync'), 'room_availability', ['last_wubook_sync'], unique=False)
    op.create_index(op.f('ix_room_availability_sync_pending'), 'room_availability', ['sync_pending'], unique=False)
    op.create_index(op.f('ix_room_availability_wubook_synced'), 'room_availability', ['wubook_synced'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_availability_wubook_synced'), table_name='room_availability')
    op.drop_index(op.f('ix_room_availability_sync_pending'), table_name='room_availability')
    op.drop_index(op.f('ix_room_availability_last_wubook_sync'), table_name='room_availability')
    op.drop_index(op.f('ix_room_availability_is_bookable'), table_name='room_availability')
    op.drop_column('room_availability', 'is_bookable')
    op.drop_column('room_availability', 'last_wubook_sync')
    op.drop_column('room_availability', 'wubook_sync_error')
    op.drop_column('room_availability', 'wubook_synced')
    op.drop_column('room_availability', 'sync_pending')
    # ### end Alembic commands ###