"""fix room unique constraint for soft delete

Revision ID: 1168eead17f6
Revises: 2cb7db9b6b42
Create Date: 2025-10-10 20:20:47.596666-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1168eead17f6'
down_revision = '2cb7db9b6b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_room_per_property', 'rooms', type_='unique')
    op.create_index('uq_active_room_per_property', 'rooms', ['tenant_id', 'property_id', 'room_number'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_room_per_property', table_name='rooms', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint('unique_room_per_property', 'rooms', ['property_id', 'room_number'])
    # ### end Alembic commands ###